### ISSUE TITLE
[Novo Repositório] Derivar links à partir das Notas Explicativas

### ISSUE THREAD

**Issue by nitaibezerra** [mdicgovbr/Portal-NBS#16]
Praticamente toda Nota Explicativa faz referências à outros serviços como forma de desambiguar cada conceito.

A ideia desta tarefa é criar links para as páginas dos Serviços referenciados nas Notas de Escopo. Dessa maneira o usuário pode navegar facilmente entre os serviços relacionados.

A imagem abaixo, por exemplo, faz referêcia à outros 3 tipos de serviços:

![image.png](https://images.zenhubusercontent.com/5a9f36aa4b5806bc2bc9b603/8c8b3aa8-e70a-462c-9a94-b2013aab163b)

**Comment by EzequielDeOliveira** [comment]
REGEX: [0-9]{1}\.[0-9]{2}([0-9]{2})?(\.[0-9])?([0-9])?(\.[0-9]{2})?
