### ISSUE TITLE
Tornar a busca Case Insensitive

### ISSUE THREAD

**Issue by EzequielDeOliveira** [mdicgovbr/Portal-NBS#38]
Essas duas buscas retornam resultados diferentes:

* http://cgse.des.mdic.gov.br/pt/search.html?utf8=%E2%9C%93&q=m%C3%BAsica&qt=contains&for=all&c=&l%5B%5D=en&l%5B%5D=pt&change_note_type=&change_note_date_from=&change_note_date_to=&pref=Buscar+nas+Notas+Explicativas
* http://cgse.des.mdic.gov.br/pt/search.html?utf8=%E2%9C%93&q=musica&qt=contains&for=all&c=&l%5B%5D=en&l%5B%5D=pt&change_note_type=&change_note_date_from=&change_note_date_to=&pref=Buscar+nas+Notas+Explicativas

**Comment by nitaibezerra** [comment]
Esta issue foi implementada parcialmente. Ainda é necessário automatizar no postgresql a execução da seguinte query para habilitar a função que remove os acentos no BD:
"CREATE EXTENSION unaccent;"

Essa dica foi encontrada em https://stackoverflow.com/questions/13596638/function-to-remove-accents-in-postgresql
