### ISSUE TITLE
Criar script que identifica referências incorretas nas Notas Explicativas

### ISSUE THREAD

**Issue by gdeusdara** [mdicgovbr/Portal-NBS#52]
Algumas Notas Explicativas possui referências (#16) à Códigos NBS inexistentes. Ou seja, são erros humanos na redação das NEBS. Considerando que este erro pode ter acontecido com diversas NEBS, precisamos listar as NEBS, e os respectivos códigos incorretos, de forma automática.

Para isso sugiro reutilizar parte do script do gerador de Links, uma vez que aquele já realiza parte das etapas necessárias.

**Comment by EzequielDeOliveira** [comment]
Código 1.0903.92 referenciado na NEBS da NBS 1.0903.37.00 está incorreto
Código 1.1703.90 referenciado na NEBS da NBS 1.0905.40.00 está incorreto
Código 1.2702.30 referenciado na NEBS da NBS 1.1409.30.00 está incorreto
 Código 1.1403.20 referenciado na NEBS da NBS 1.1410.90.00 está incorreto
Código 1.1501.50 referenciado na NEBS da NBS 1.1506.2 está incorreto
Código 1.1506.40 referenciado na NEBS da NBS 1.1506.23.00 está incorreto

**Comment by gdeusdara** [comment]
Tem que mandar Email, @nitaibezerra !!
